
import type { Product, Category, Order } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Consoles' },
  { id: '2', name: 'Jogos' },
  { id: '3', name: 'Acessórios' },
  { id: '4', name: 'Periféricos' },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'playstation-5',
    name: 'PlayStation 5',
    description: 'Experimente um carregamento ultrarrápido com um SSD de altíssima velocidade, imersão mais profunda com suporte para feedback tátil, gatilhos adaptáveis e áudio 3D.',
    price: 4499.99,
    categoryId: '1',
    brand: 'Sony',
    rating: 5,
    stock: 15,
    imagePlaceholderId: 'ps5-console',
  },
  {
    id: '2',
    slug: 'xbox-series-x',
    name: 'Xbox Series X',
    description: 'O Xbox mais rápido e poderoso de todos os tempos. Explore novos mundos ricos com 12 teraflops de poder de processamento gráfico bruto, DirectX ray tracing, um SSD personalizado e jogos 4K.',
    price: 4349.00,
    categoryId: '1',
    brand: 'Microsoft',
    rating: 4.9,
    stock: 12,
    imagePlaceholderId: 'xbox-series-x',
  },
  {
    id: '3',
    slug: 'nintendo-switch-oled',
    name: 'Nintendo Switch OLED',
    description: 'Jogue em casa na TV ou em qualquer lugar com uma vibrante tela OLED de 7 polegadas. Além da nova tela com cores vivas e contraste nítido, o Nintendo Switch (modelo OLED) inclui um amplo suporte ajustável.',
    price: 2499.99,
    categoryId: '1',
    brand: 'Nintendo',
    rating: 4.8,
    stock: 25,
    imagePlaceholderId: 'nintendo-switch',
  },
  {
    id: '4',
    slug: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    description: 'Uma história de ação e aventura de mundo aberto ambientada em Night City, uma megalópole obcecada por poder, glamour e modificação corporal.',
    price: 199.90,
    categoryId: '2',
    brand: 'CD Projekt Red',
    rating: 4.5,
    stock: 50,
    imagePlaceholderId: 'cyberpunk-2077',
  },
  {
    id: '5',
    slug: 'elden-ring',
    name: 'Elden Ring',
    description: 'Levante-se, Maculado, e seja guiado pela graça para brandir o poder do Anel Prístino e se tornar um Lorde Prístino nas Terras Intermédias.',
    price: 249.99,
    categoryId: '2',
    brand: 'FromSoftware',
    rating: 5,
    stock: 40,
    imagePlaceholderId: 'elden-ring',
  },
  {
    id: '6',
    slug: 'headset-gamer-sem-fio',
    name: 'Headset Gamer Sem Fio',
    description: 'Headset sem fio com som surround 7.1, microfone com cancelamento de ruído e bateria de longa duração para longas sessões de jogo.',
    price: 799.90,
    categoryId: '3',
    brand: 'GamerGear',
    rating: 4.7,
    stock: 30,
    imagePlaceholderId: 'gaming-headset',
  },
  {
    id: '7',
    slug: 'controle-pro-elite',
    name: 'Controle Pro Elite',
    description: 'Controle de nível profissional com botões traseiros personalizáveis, thumbsticks intercambiáveis e gatilhos com trava para uma resposta mais rápida.',
    price: 999.00,
    categoryId: '3',
    brand: 'PowerPlay',
    rating: 4.9,
    stock: 20,
    imagePlaceholderId: 'pro-controller',
  },
  {
    id: '8',
    slug: 'teclado-mecanico-rgb',
    name: 'Teclado Mecânico RGB',
    description: 'Teclado mecânico para jogos com switches de alta performance, iluminação RGB por tecla e design de alumínio durável.',
    price: 649.50,
    categoryId: '4',
    brand: 'TechGamer',
    rating: 4.8,
    stock: 35,
    imagePlaceholderId: 'mechanical-keyboard',
  },
  {
    id: '9',
    slug: 'mouse-gamer-ultraleve',
    name: 'Mouse Gamer Ultraleve',
    description: 'Mouse ultraleve com sensor óptico de alta precisão, design ergonômico e iluminação RGB para máxima performance e estilo.',
    price: 399.99,
    categoryId: '4',
    brand: 'GamerGear',
    rating: 4.6,
    stock: 45,
    imagePlaceholderId: 'gaming-mouse',
  },
  {
    id: '10',
    slug: 'the-legend-of-zelda-tears-of-the-kingdom',
    name: 'The Legend of Zelda: Tears of the Kingdom',
    description: 'Uma aventura épica pelas terras e céus de Hyrule aguarda. Crie seu próprio caminho nestes mundos abertos e emocionantes.',
    price: 349.90,
    categoryId: '2',
    brand: 'Nintendo',
    rating: 5,
    stock: 60,
    imagePlaceholderId: 'zelda-totk',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-12345',
    userId: 'firebase-uid-1', // This will now be matched against Firebase User UID
    items: [
      { id: '4', name: 'Cyberpunk 2077', price: 199.90, quantity: 1, image: 'cyberpunk-2077' },
      { id: '6', name: 'Headset Gamer Sem Fio', price: 799.90, quantity: 1, image: 'gaming-headset' },
    ],
    total: 999.80,
    date: '2024-05-10T10:30:00Z',
    shippingAddress: 'Rua dos Gamers, 123, Bairro dos Controles, São Paulo, SP, 01234-567',
    status: 'Entregue',
  }
];
